# Generated by Django 3.1 on 2020-08-23 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personprofile',
            old_name='Resume',
            new_name='resume',
        ),
    ]
