# Generated by Django 3.1 on 2020-08-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200823_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Company'), (2, 'Person'), (3, 'Admin')], default=3),
        ),
    ]
